# Generated by Django 2.2.6 on 2019-11-12 12:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, unique=True, verbose_name='用户名')),
                ('account', models.CharField(default='', max_length=20, verbose_name='账号')),
                ('password', models.CharField(max_length=150, verbose_name='密码')),
                ('email', models.CharField(max_length=20, null=True, verbose_name='邮箱')),
                ('u_image', models.CharField(default='', max_length=20, verbose_name='头像')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('intro', models.CharField(max_length=100, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='大学名称')),
                ('intro', models.CharField(max_length=50, verbose_name='大学简介')),
                ('logo', models.CharField(max_length=50, verbose_name='大学 logo')),
                ('co_image', models.CharField(max_length=50, verbose_name='大学图片')),
                ('schoolbadge', models.CharField(max_length=50, verbose_name='大学背景图片')),
            ],
            options={
                'verbose_name': '大学',
                'verbose_name_plural': '大学',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='课程名称')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('intro', models.CharField(max_length=50, verbose_name='课程简介')),
                ('v_image', models.CharField(max_length=30, verbose_name='课程图片地址')),
                ('viewnum', models.IntegerField(verbose_name='观看数量')),
                ('likenum', models.IntegerField(verbose_name='点赞数量')),
                ('collectnum', models.IntegerField(verbose_name='收藏数量')),
                ('coursefile', models.CharField(max_length=30, verbose_name='课件')),
                ('sumtime', models.IntegerField(verbose_name='课程总时长')),
                ('classifyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Classify')),
                ('collegeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.College')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoid', models.CharField(max_length=30, verbose_name='视频地址')),
                ('sectionname', models.CharField(max_length=30, verbose_name='视频章节名称')),
                ('time', models.CharField(max_length=20, verbose_name='视频时长')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Course')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='资料名称')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('intro', models.CharField(max_length=50, verbose_name='资料简介')),
                ('downloadnum', models.IntegerField(verbose_name='下载数量')),
                ('m_image', models.CharField(max_length=20, verbose_name='资料简介')),
                ('classifyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Classify')),
            ],
            options={
                'verbose_name': '资料',
                'verbose_name_plural': '资料',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historytime', models.CharField(max_length=50, null=True, verbose_name='历史时间')),
                ('collect', models.BooleanField(default=False, verbose_name='收藏')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Video')),
            ],
            options={
                'verbose_name': '观看历史',
                'verbose_name_plural': '观看历史',
            },
        ),
    ]
