# Generated by Django 2.2.6 on 2019-11-13 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classifyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Classify', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='course',
            name='collegeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.College', verbose_name='所属大学'),
        ),
        migrations.AlterField(
            model_name='history',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='history',
            name='videoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Video', verbose_name='所属视频'),
        ),
        migrations.AlterField(
            model_name='material',
            name='classifyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Classify', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='material',
            name='m_image',
            field=models.CharField(max_length=20, verbose_name='资料图片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_image',
            field=models.ImageField(default='', upload_to='avatar/%Y/%m', verbose_name='头像图片路径'),
        ),
        migrations.AlterField(
            model_name='video',
            name='courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Course', verbose_name='所设课程'),
        ),
    ]
