# Generated by Django 2.2.6 on 2019-11-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191113_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_image',
            field=models.ImageField(height_field='url_height', upload_to='uploads/%Y/%m/%d/', verbose_name='头像图片路径', width_field='url_width'),
        ),
    ]
